#!/usr/bin/env bash

IFS=$'\n'

dir="${1}"
if [[ -z "${dir}" ]]; then
    echo "No dir specified"
    exit 1
fi

for file in $(find "${dir}" -type f); do
    stat_raw="$(stat -c '%s %X' "${file}")"
    size=$(stat -c '%s' "${file}")
    size=$(numfmt --to=iec-i --format=%.1f --round=nearest "${size}" \
        | sed 's/\([a-zA-Z]*\)$/ \1B/g')
    access=$(stat -c '%X' "${file}")
    access=$(date --date="@${access}" +'%b %d %Y')

    printf "%10s | %11s | %s\n" "${size}" "${access}" "${file}"
done 
